const en = {
  title: 'Friend duel', subtitle: 'Your secret. Your answers. A live geography duel for two.',
  multiplayer: 'Play with a friend', play_countrydle: 'Guess the Country', play_us_statedle: 'Guess the US State', play_wojewodztwodle: 'Guess the Voivodeship', play_powiatdle: 'Guess the County', play_europe: 'Guess the European Nation', play_asia: 'Guess the Asian Nation', play_africa: 'Guess the African Nation', play_americas: 'Guess the American Nation',
  atlas: 'Atlas', searchArea: 'Search area', mapHelp: 'Mark locations on the map to keep track of your ideas. Your marks are private.',
  turnHelp: 'Ask a question or make a guess. Each uses your turn.', questionPlaceholder: 'Ask a yes-or-no question…', choose: 'Choose',
  questionHistory: 'Question history', noQuestions: 'Ask your first question to start narrowing down the map.', noGuesses: 'Your guesses will appear here.', rulesTitle: 'How to play',
  rules: 'Each player chooses their own secret. Take turns asking a question OR making a guess. Every guess spends a turn; there is no guess limit. Answer your friend yourself — private AI advice never holds up play.',
  create: 'Create an invite', name: 'Your guest name', mode: 'Geography', join: 'Join duel',
  countrydle: 'World countries', europe: 'Europe (Europedle)', asia: 'Asia (Asiadle)', africa: 'Africa (Africadle)', americas: 'Americas (Americadle)', us_statedle: 'US states', wojewodztwodle: 'Polish voivodeships', powiatdle: 'Polish counties',
  groupGlobal: 'Global', groupContinents: 'Continents', groupRegional: 'Regional Maps',
  loading: 'Loading duel…', error: 'Could not complete the request. Check your connection and try again.',
  stale: 'The duel changed before this action arrived. The latest state is shown; choose your action again.',
  refresh: 'Refresh state', retry: 'Retry the same request', uncertain: 'The request may already have arrived. Retry safely before taking another action.',
  invite: 'Invite a friend', copy: 'Copy invite link', copied: 'Link copied', share: 'Share invite', copyFailed: 'Copy unavailable. Select and copy the link below.',
  full: 'This invitation link has expired — both seats are already taken. Create a new duel to play with a friend.',
  ended: 'This duel has ended and this link has expired. Only its players can view the results.',
  joining: 'Joining', guest: 'No account needed. Your seat is saved in this browser’s cookie. Keep this link to resume.',
  collection: 'We save questions, human answers and AI recommendations to check agreement and improve question answering. AI explanations are visible only to the country owner and authorized reviewers.',
  privacy: 'Privacy and retention',
  lobby: 'Lobby', waitingFriend: 'Waiting for your friend to join…', waitingReady: 'Both players must be connected and ready to begin.',
  secret: 'Secret', chooseSecretOnMap: 'Click map or randomize', secretHelp: 'Click your secret location directly on the map, or choose randomly. Then click Accept & Ready.',
  search: 'Search locations', select: 'Select a location', noMatches: 'No matching locations.', random: 'Random secret',
  saveSecret: 'Use this secret', acceptAndReady: 'Accept & Ready', ready: 'Ready to play', notReady: 'Not ready', unready: 'Change secret',
  you: 'You', connected: 'Connected', disconnected: 'Disconnected', connecting: 'Connecting…', recovering: 'Reconnecting — syncing over HTTP',
  turn: 'Turn', deadline: 'Time remaining', expired: 'Waiting for server decision…', yourTurn: 'Your turn', theirTurn: 'Your friend is choosing a move.',
  answering: 'Answer your friend', awaitingAnswer: 'Waiting for your friend’s answer. AI never decides or delays their response.',
  reply: 'Final reply: guess correctly to draw, or pass. Questions are not available on this reply.',
  question: 'Your question', ask: 'Ask and spend this turn', guess: 'Guess a location', submitGuess: 'Submit selected guess', pass: 'Pass this turn',
  unlimited: 'Unlimited guesses. Counts describe moves made — they are not quotas.', questions: 'Questions', guesses: 'Guesses',
  yes: 'Yes', mostly_yes: 'Yes-ish', mostly_no: 'No-ish', no: 'No', unknown: 'I don’t know',
  ai: 'Private AI advice', aiHelp: 'Only you see this advice for your own secret. Choose any answer now; you never need to wait.',
  aiPending: 'AI is checking independently…', aiFailed: 'AI advice is unavailable. You can still answer immediately.',
  aiNoExplanation: 'The AI returned an answer without an explanation.',
  YES: 'YES', NO: 'NO', INVALID: 'INVALID', late: 'Arrived after the human answer', source: 'Source',
  history: 'Public moves', noHistory: 'Moves will appear here. Only the human answer is shared — no AI advice or notes.',
  passed: 'Passed', correct: 'Correct guess', incorrect: 'Incorrect guess', pending: 'Awaiting answer', revision: 'Revision',
  correctAnswer: 'Correct my answer', saveCorrection: 'Publish correction', cancel: 'Cancel', older: 'Load older moves',
  privateHistory: 'Your private AI history', privateHistoryHelp: 'Includes late advice. Never shared with your opponent, even after the match.',
  offerDraw: 'Offer a draw', drawOffered: 'Your draw offer is pending. The turn clock keeps running.', drawReceived: 'Your friend offered a draw. The clock keeps running.', acceptDraw: 'Accept draw', declineDraw: 'Decline draw',
  leave: 'Leave duel', leaveConfirm: 'Leave this duel? During play this forfeits your game.',
  results: 'Duel results', won: 'You won', lost: 'Your friend won', draw: 'Draw', solved: 'Solved', forfeit: 'Forfeit', interrupted: 'Interrupted — no competitive result', cancelled: 'Duel cancelled',
  reveals: 'The secrets', rematch: 'Request a rematch', rematchWaiting: 'You requested a rematch. Waiting for your friend…', rematchReceived: 'Your friend wants a rematch. Accept to start with fresh secrets.', rematchOpen: 'Open rematch',
  report: 'Report answer', reportHelp: 'Describe a factual issue. Reports go to review, not to your opponent. They never rewrite the result.', sendReport: 'Send report', reported: 'Report submitted', newDuel: 'Create another duel', wins: 'Wins', draws: 'Draws',
  noEntities: 'The location list is unavailable. Retry before choosing a secret or guess.', showSecret: 'Show secret', hideSecret: 'Hide secret',
  timedOut: 'Time expired — automatic pass', unanswered: 'No human answer — time expired',
  timeoutWarning: 'Consecutive timeouts', timeoutRules: 'Thinking: 45 seconds. Answering: 30 seconds. A first timeout passes the turn without inventing an answer; a second consecutive timeout forfeits. A final reply timeout awards the pending win.',
  allMoves: 'All moves', yourMoves: 'Your moves', friendMoves: 'Friend’s moves',
  expandMap: 'Expand map', collapseMap: 'Compact map', actionRequired: 'Action required',
  yourTurnToAct: 'Your turn to move', waitingForFriend: 'Waiting for friend', waitingForAnswer: 'Waiting for answer',
  youAsked: 'You asked', friendAsked: 'Friend asked', youGuessed: 'You guessed', friendGuessed: 'Friend guessed',
  youPassed: 'You passed', friendPassed: 'Friend passed', activeTurn: 'Active turn', waiting: 'Waiting',
  askQuestionTab: 'Ask Question', makeGuessTab: 'Make Guess', intelHistory: 'Intel & History',
} as const;

type DuelCopy = { [K in keyof typeof en]: string };
const pl: DuelCopy = {
  title: 'Pojedynek ze znajomym', subtitle: 'Twój sekret. Twoje odpowiedzi. Geograficzny pojedynek na żywo.',
  multiplayer: 'Zagraj ze znajomym', play_countrydle: 'Zgadnij kraj', play_us_statedle: 'Zgadnij stan USA', play_wojewodztwodle: 'Zgadnij województwo', play_powiatdle: 'Zgadnij powiat', play_europe: 'Zgadnij kraj w Europie', play_asia: 'Zgadnij kraj w Azji', play_africa: 'Zgadnij kraj w Afryce', play_americas: 'Zgadnij kraj w Amerykach',
  atlas: 'Atlas', searchArea: 'Obszar poszukiwań', mapHelp: 'Zaznaczaj miejsca na mapie, aby śledzić swoje pomysły. Tylko Ty widzisz te oznaczenia.',
  turnHelp: 'Zadaj pytanie albo zgaduj. Każda operacja zużywa turę.', questionPlaceholder: 'Zadaj pytanie typu tak lub nie…', choose: 'Wybierz',
  questionHistory: 'Historia pytań', noQuestions: 'Zadaj pierwsze pytanie i zawęź obszar poszukiwań.', noGuesses: 'Tutaj pojawią się Twoje próby.', rulesTitle: 'Jak grać',
  rules: 'Każdy wybiera własny sekret. W swojej turze zadajesz pytanie ALBO zgadujesz. Każda próba zużywa turę; liczba prób jest nieograniczona. Odpowiadasz samodzielnie — prywatna rada AI nigdy nie wstrzymuje gry.',
  create: 'Utwórz zaproszenie', name: 'Twoja nazwa gracza', mode: 'Geografia', join: 'Dołącz do pojedynku',
  countrydle: 'Kraje świata', europe: 'Europa (Europedle)', asia: 'Azja (Asiadle)', africa: 'Afryka (Africadle)', americas: 'Ameryki (Americadle)', us_statedle: 'Stany USA', wojewodztwodle: 'Województwa', powiatdle: 'Powiaty',
  groupGlobal: 'Globalne', groupContinents: 'Kontynenty', groupRegional: 'Regionalne',
  loading: 'Wczytywanie pojedynku…', error: 'Nie udało się wykonać operacji. Sprawdź połączenie i spróbuj ponownie.',
  stale: 'Stan gry zmienił się przed odebraniem operacji. Wczytano aktualny stan — ponownie wybierz ruch.',
  refresh: 'Odśwież stan', retry: 'Ponów tę samą operację', uncertain: 'Operacja mogła już dotrzeć. Bezpiecznie ponów ją przed następnym ruchem.',
  invite: 'Zaproś znajomego', copy: 'Kopiuj link zaproszenia', copied: 'Skopiowano link', share: 'Udostępnij zaproszenie', copyFailed: 'Kopiowanie niedostępne. Zaznacz i skopiuj link poniżej.',
  full: 'Ten link z zaproszeniem wygasł — oba miejsca zostały już zajęte. Utwórz nowy pojedynek, aby zagrać ze znajomym.',
  ended: 'Ten pojedynek został zakończony, a link wygasł. Wyniki mogą zobaczyć tylko jego gracze.',
  joining: 'Dołączanie', guest: 'Konto nie jest potrzebne. Twoje miejsce zapisuje ciasteczko tej przeglądarki. Zachowaj link, aby wrócić.',
  collection: 'Zapisujemy pytania, odpowiedzi graczy i rekomendacje AI, aby porównywać ich zgodność i ulepszać odpowiedzi. Wyjaśnienia AI widzi tylko właściciel sekretu i uprawnieni administratorzy.',
  privacy: 'Prywatność i przechowywanie danych',
  lobby: 'Poczekalnia', waitingFriend: 'Czekamy na znajomego…', waitingReady: 'Obaj gracze muszą być połączeni i gotowi, aby rozpocząć.',
  secret: 'Sekret', chooseSecretOnMap: 'Kliknij mapę lub wylosuj', secretHelp: 'Kliknij swoje sekretne miejsce bezpośrednio na mapie lub wylosuj. Następnie kliknij Zaakceptuj i graj.',
  search: 'Szukaj miejsca', select: 'Wybierz miejsce', noMatches: 'Brak pasujących miejsc.', random: 'Wylosuj sekret',
  saveSecret: 'Ustaw ten sekret', acceptAndReady: 'Zaakceptuj i graj', ready: 'Gotowość do gry', notReady: 'Brak gotowości', unready: 'Zmień sekret',
  you: 'Ty', connected: 'Połączono', disconnected: 'Rozłączono', connecting: 'Łączenie…', recovering: 'Ponowne łączenie — synchronizacja przez HTTP',
  turn: 'Tura', deadline: 'Pozostały czas', expired: 'Oczekiwanie na decyzję serwera…', yourTurn: 'Twoja tura', theirTurn: 'Znajomy wybiera ruch.',
  answering: 'Odpowiedz znajomemu', awaitingAnswer: 'Czekamy na odpowiedź znajomego. AI nie decyduje ani nie opóźnia odpowiedzi.',
  reply: 'Ostatnia szansa: traf, aby zremisować, albo spasuj. W tej turze nie można zadawać pytań.',
  question: 'Twoje pytanie', ask: 'Zapytaj i zużyj turę', guess: 'Zgadnij miejsce', submitGuess: 'Zatwierdź wybraną odpowiedź', pass: 'Spasuj w tej turze',
  unlimited: 'Próby bez limitu. Liczniki pokazują wykonane ruchy — nie są limitami.', questions: 'Pytania', guesses: 'Próby',
  yes: 'Tak', mostly_yes: 'Raczej tak', mostly_no: 'Raczej nie', no: 'Nie', unknown: 'Nie wiem',
  ai: 'Prywatna rada AI', aiHelp: 'Tylko Ty widzisz radę dotyczącą własnego sekretu. Odpowiedz od razu — nie musisz czekać.',
  aiPending: 'AI niezależnie sprawdza odpowiedź…', aiFailed: 'Rada AI jest niedostępna. Nadal możesz od razu odpowiedzieć.',
  aiNoExplanation: 'AI zwróciło odpowiedź bez wyjaśnienia.',
  YES: 'TAK', NO: 'NIE', INVALID: 'NIEPRAWIDŁOWE PYTANIE', late: 'Otrzymano po odpowiedzi gracza', source: 'Źródło',
  history: 'Publiczne ruchy', noHistory: 'Tutaj pojawią się ruchy. Udostępniamy tylko odpowiedź gracza — bez rad AI i notatek.',
  passed: 'Pas', correct: 'Trafna odpowiedź', incorrect: 'Błędna odpowiedź', pending: 'Oczekiwanie na odpowiedź', revision: 'Wersja',
  correctAnswer: 'Popraw moją odpowiedź', saveCorrection: 'Opublikuj poprawkę', cancel: 'Anuluj', older: 'Wczytaj starsze ruchy',
  privateHistory: 'Twoja prywatna historia AI', privateHistoryHelp: 'Obejmuje spóźnione rady. Nigdy nie trafia do przeciwnika, nawet po zakończeniu gry.',
  offerDraw: 'Zaproponuj remis', drawOffered: 'Twoja propozycja remisu oczekuje. Czas tury nadal biegnie.', drawReceived: 'Znajomy proponuje remis. Czas nadal biegnie.', acceptDraw: 'Przyjmij remis', declineDraw: 'Odrzuć remis',
  leave: 'Opuść pojedynek', leaveConfirm: 'Opuścić pojedynek? W trakcie gry oznacza to przegraną walkowerem.',
  results: 'Wyniki pojedynku', won: 'Wygrywasz', lost: 'Znajomy wygrywa', draw: 'Remis', solved: 'Odgadnięto', forfeit: 'Walkower', interrupted: 'Gra przerwana — bez wyniku sportowego', cancelled: 'Pojedynek anulowany',
  reveals: 'Sekrety graczy', rematch: 'Zaproponuj rewanż', rematchWaiting: 'Zaproponowano rewanż. Czekamy na znajomego…', rematchReceived: 'Znajomy chce rewanżu. Przyjmij, aby zacząć z nowymi sekretami.', rematchOpen: 'Otwórz rewanż',
  report: 'Zgłoś odpowiedź', reportHelp: 'Opisz błąd merytoryczny. Zgłoszenie trafi do weryfikacji, nie do przeciwnika. Nie zmienia wyniku gry.', sendReport: 'Wyślij zgłoszenie', reported: 'Wysłano zgłoszenie', newDuel: 'Utwórz nowy pojedynek', wins: 'Wygrane', draws: 'Remisy',
  noEntities: 'Lista miejsc jest niedostępna. Ponów wczytanie przed wyborem sekretu lub odpowiedzi.', showSecret: 'Pokaż sekret', hideSecret: 'Ukryj sekret',
  timedOut: 'Czas minął — automatyczny pas', unanswered: 'Brak odpowiedzi gracza — czas minął',
  timeoutWarning: 'Kolejne przekroczenia czasu', timeoutRules: 'Ruch: 45 sekund. Odpowiedź: 30 sekund. Pierwsze przekroczenie czasu oddaje turę bez wymyślania odpowiedzi; drugie z rzędu oznacza walkower. Upływ czasu ostatniej szansy przyznaje oczekujące zwycięstwo.',
  allMoves: 'Wszystkie ruchy', yourMoves: 'Twoje ruchy', friendMoves: 'Ruchy znajomego',
  expandMap: 'Rozwiń mapę', collapseMap: 'Zwiń mapę', actionRequired: 'Wymagana odpowiedź',
  yourTurnToAct: 'Twoja kolej na ruch', waitingForFriend: 'Oczekiwanie na znajomego', waitingForAnswer: 'Oczekiwanie na odpowiedź',
  youAsked: 'Twoje pytanie', friendAsked: 'Pytanie znajomego', youGuessed: 'Twój strzał', friendGuessed: 'Strzał znajomego',
  youPassed: 'Pas', friendPassed: 'Znajomy spasował', activeTurn: 'Aktywna tura', waiting: 'Czeka',
  askQuestionTab: 'Zadaj pytanie', makeGuessTab: 'Zgadnij miejsce', intelHistory: 'Historia wywiadu',
};
export type { DuelCopy };
export function duelCopy(language: string): DuelCopy { return language.startsWith('pl') ? pl : en; }
export const duelModes = ['countrydle', 'europe', 'asia', 'africa', 'americas', 'us_statedle', 'wojewodztwodle', 'powiatdle'] as const;
export const humanAnswers = ['yes', 'mostly_yes', 'mostly_no', 'no', 'unknown'] as const;
export const duelPanel = 'rounded-sm border border-white/10 bg-obsidian-900 p-4 sm:p-5';
export const duelButton = 'min-h-10 rounded-sm border border-white/15 px-3 py-2 text-sm font-medium text-sand-100 transition-colors hover:bg-white/5 disabled:cursor-not-allowed disabled:opacity-40';
export const duelPrimary = `${duelButton} border-emerald-400 bg-emerald-400 text-obsidian-950 hover:bg-emerald-300`;
export const duelInput = 'w-full rounded-sm border border-white/15 bg-obsidian-950 px-3 py-3 text-sm text-sand-100 focus:border-emerald-500/70 focus:outline-none focus:ring-1 focus:ring-emerald-500/30 disabled:opacity-40';
